// MOCK_DB — contenido educativo estático, con la misma forma que tendrá la
// futura respuesta de WordPress (mobile_content-equivalente ya parseado).
// Los datos del USUARIO (movimientos, vencimientos, perfil) no viven acá —
// viven 100% en localStorage, ver STORAGE_KEYS en app.js.

const MOCK_DB = {
  contentCategories: [
    { id: 'tips-financieros',      name: 'Tips Financieros' },
    { id: 'alertas',               name: 'Alertas' },
    { id: 'ahorro',                name: 'Ahorro' },
    { id: 'educacion-financiera',  name: 'Educación Financiera' },
  ],

  tips: [
    {
      id: 'auditoria-suscripciones-fantasma',
      categoryId: 'alertas',
      badge: 'Alertas',
      title: 'Auditoría de Suscripciones Fantasma',
      excerpt: 'Una vez al mes, repasá tus movimientos: ahí se esconden los cobros de servicios que ya no usás.',
      image: 'assets/tips/auditoria-suscripciones-fantasma.jpg',
      body: [
        'Con tantos servicios cobrando en automático, es fácil perder de vista una suscripción que dejaste de usar hace meses — pero el cobro sigue llegando igual, mes tras mes.',
        'Reservá un momento fijo cada mes para revisar tus movimientos bancarios línea por línea. Por cada cobro recurrente —una app, un gimnasio, un streaming— preguntate si de verdad lo seguís usando.',
        'Un cobro chico que parece inofensivo puede sumar una cifra considerable al cabo de un año si nadie lo nota. Cancelar lo que ya no usás es plata que vuelve directo a tu bolsillo, sin cambiar en nada tu día a día.',
      ],
      publishedAt: '2026-08-23',
    },
    {
      id: 'pagate-a-ti-primero',
      categoryId: 'ahorro',
      badge: 'Ahorro',
      title: 'Automatización de los Ahorros',
      excerpt: 'Programá el ahorro para el mismo día que te pagan. Tratalo como una factura más, no como lo que sobra.',
      image: 'assets/tips/pagate-a-ti-primero.jpg',
      body: [
        'La mayoría intenta ahorrar con lo que sobra a fin de mes — y casi nunca sobra nada, porque el gasto se expande hasta ocupar todo lo disponible.',
        'El principio de pagarte a vos primero da vuelta esa lógica: consiste en programar una transferencia automática a tu cuenta de ahorro el mismo día que te pagan. Al tratar el ahorro como una obligación fija e inamovible, aprendés a vivir cómodo con el resto.',
        'No hace falta depender de la fuerza de voluntad: una vez que la transferencia es automática, el hábito se sostiene solo, mes tras mes.',
      ],
      publishedAt: '2026-08-16',
    },
    {
      id: 'fondo-emergencia',
      categoryId: 'educacion-financiera',
      badge: 'Educación Financiera',
      title: 'Creación del Fondo de Emergencia',
      excerpt: 'Antes de invertir o hacer una compra grande, armá un colchón que cubra entre 3 y 6 meses de tus gastos fijos.',
      image: 'assets/tips/fondo-emergencia.jpg',
      body: [
        'Un fondo de emergencia tiene un solo trabajo: estar disponible en efectivo el día que algo se rompe, alguien se enferma o el ingreso se corta un mes. No busca rendimiento — busca estar ahí, líquido y accesible.',
        'La referencia habitual es cubrir entre tres y seis meses de tus gastos fijos de subsistencia. No es un fondo para invertir ni para gastos recreativos — es exclusivamente para imprevistos inevitables.',
        'Tenerlo armado no evita los imprevistos, pero sí evita que un imprevisto te obligue a pedir un préstamo caro o tirar de la tarjeta de crédito.',
      ],
      publishedAt: '2026-08-09',
    },
    {
      id: 'presupuesto-base-cero',
      categoryId: 'tips-financieros',
      badge: 'Tips Financieros',
      title: 'El Hábito del Presupuesto Base Cero',
      excerpt: 'Ingresos − Gastos − Ahorro = 0. Asignale un propósito a cada peso antes de que empiece el mes.',
      image: 'assets/tips/presupuesto-base-cero.jpg',
      body: [
        'La idea del presupuesto base cero es simple: cada peso que entra a tu cuenta debe tener un destino asignado antes de que arranque el mes. La ecuación es Ingresos − Gastos − Ahorro = 0.',
        'Esto no significa dejar la cuenta en cero ni gastarlo todo — significa asignar conscientemente cada saldo a una categoría específica, incluyendo un margen para imprevistos o para darte un gusto.',
        'Si el dinero no tiene una tarea asignada desde el día uno, tiende a irse solo en gastos chicos y cotidianos sin que te des cuenta.',
      ],
      publishedAt: '2026-08-02',
    },
    {
      id: 'metodo-bola-de-nieve',
      categoryId: 'educacion-financiera',
      badge: 'Educación Financiera',
      title: 'Eliminación de Deudas: Método Bola de Nieve',
      excerpt: 'Ordená tus deudas de menor a mayor y atacá primero la más chica. Las victorias rápidas sostienen el hábito.',
      image: 'assets/tips/metodo-bola-de-nieve.jpg',
      body: [
        'Este método prioriza la motivación por sobre la matemática pura: en vez de atacar primero la deuda con mayor interés, ordená todas tus deudas de menor a mayor saldo pendiente.',
        'Pagá el mínimo en todas y destiná cualquier plata extra a liquidar la más chica. Al saldarla rápido, ganás una victoria emocional que refuerza el hábito — y lo que pagabas en esa cuota se suma a la siguiente deuda.',
        'Así se arma un efecto acumulativo: cada deuda que cae libera más plata para atacar la siguiente, cada vez más grande, hasta que no queda ninguna.',
      ],
      publishedAt: '2026-07-26',
    },
    {
      id: 'menu-semanal-compras',
      categoryId: 'ahorro',
      badge: 'Ahorro',
      title: 'Estrategia del Menú Semanal',
      excerpt: 'Planificá el menú de la semana antes de ir de compras. Una lista estricta reduce el desperdicio hasta un 30%.',
      image: 'assets/tips/menu-semanal-compras.jpg',
      body: [
        'La comida es una de las áreas donde más plata se desperdicia por falta de planificación: se compra de más, se repiten productos y algo perecedero termina en la basura.',
        'Diseñar un menú semanal antes de salir te permite armar una lista de compras exacta, basada en lo que realmente vas a cocinar — sin duplicados ni sobras que no se usan.',
        'Ir al súper con una lista estricta y sin hambre reduce, además, las compras impulsivas en pasillos que no tenías pensado visitar.',
      ],
      publishedAt: '2026-07-19',
    },
    {
      id: 'gastos-hormiga',
      categoryId: 'alertas',
      badge: 'Alertas',
      title: 'Identificación de los Gastos Hormiga',
      excerpt: 'El café de todos los días, el viaje corto en auto: solos parecen nada, pero acumulados pesan en tu mes.',
      image: 'assets/tips/gastos-hormiga.jpg',
      body: [
        'Los gastos hormiga son esas sumas chicas que salen a diario en cosas prescindibles — un café para llevar, una propina no planificada, un viaje corto que podrías haber caminado.',
        'Como cada monto individual es muy bajo, el cerebro los ignora en el presupuesto diario. El problema aparece cuando los multiplicás por los 365 días del año.',
        'No se trata de eliminarlos de un día para el otro — se trata de notarlos. Esa plata, bien canalizada, puede ir directo a una meta financiera o al fondo de ahorro.',
      ],
      publishedAt: '2026-07-12',
    },
    {
      id: 'regla-50-30-20',
      categoryId: 'tips-financieros',
      badge: 'Tips Financieros',
      title: 'La Regla 50/30/20',
      excerpt: '50% a necesidades, 30% a gustos, 20% a ahorro o deudas. Un punto de partida simple para ordenar el mes.',
      image: 'assets/tips/regla-50-30-20.jpg',
      imageFit: 'contain',
      body: [
        'Es una de las formas más intuitivas de estructurar tus finanzas: dividí tus ingresos netos en tres grandes bloques.',
        'El 50% va a lo indispensable —vivienda, servicios, alimentación esencial, transporte—. El 30% a gastos de estilo de vida —salidas, entretenimiento, pasatiempos—. Y el 20% restante, exclusivamente a metas financieras: ahorro, inversión o pago acelerado de deudas.',
        'No es una ley fija — es un punto de partida que podés ajustar una vez que veas cómo se mueve tu plata en la práctica.',
      ],
      publishedAt: '2026-07-05',
    },
    {
      id: 'regla-24-horas',
      categoryId: 'tips-financieros',
      badge: 'Mindfulness Financiera',
      title: 'La Regla de las 24 Horas',
      excerpt: 'Antes de comprar algo que no estaba en tu lista, esperá un día. La urgencia casi siempre baja.',
      image: 'assets/tips/regla-24-horas.jpg',
      body: [
        'Cuando algo te genera ganas de comprarlo ya mismo, el cerebro está teniendo un pico de dopamina asociado a la novedad — no necesariamente a una necesidad real.',
        'La regla es simple: pausá la compra y esperá 24 horas antes de pagar. Durante ese tiempo de enfriamiento, el impulso emocional baja y la mente analítica toma el control.',
        'Si a las 24 horas todavía lo querés y entra en tu presupuesto, comprálo con tranquilidad — ya no es un impulso, es una decisión. Si no, habrás evitado un gasto que no ibas a necesitar.',
      ],
      publishedAt: '2026-06-28',
    },
    {
      id: 'revision-seguros',
      categoryId: 'educacion-financiera',
      badge: 'Educación Financiera',
      title: 'Revisión de Coberturas y Seguros',
      excerpt: 'Una vez al año, repasá tus pólizas. No estar bien cubierto puede costarte mucho más que la prima misma.',
      image: 'assets/tips/revision-seguros.jpg',
      body: [
        'Ordenar tus finanzas no es solo acumular ahorro — también es proteger lo que ya construiste. Un chequeo anual de tus pólizas (salud, vida, vehículo, vivienda) confirma que las sumas aseguradas siguen alineadas con tu realidad actual.',
        'Estar infrasegurado, o directamente sin cobertura, te deja expuesto: un siniestro grande puede obligarte a liquidar años de ahorro o a endeudarte para cubrirlo.',
        'No hace falta revisarlo todos los meses — pero sí una vez al año, con calma, antes de que un imprevisto te obligue a hacerlo con apuro.',
      ],
      publishedAt: '2026-06-21',
    },

    // Tanda agregada 2026-08-26 a partir de las notas en PDF del club —
    // sin foto propia todavía (assets/tips/ solo tiene .jpg para los 10 tips
    // originales); si aparecen imágenes para estos, agregar `image` acá.
    {
      id: 'automatizacion-transferencias-ahorro',
      categoryId: 'ahorro',
      badge: 'Ahorro',
      title: 'Automatización de Transferencias al Ahorro',
      excerpt: 'Configurá una transferencia automática a tu cuenta de ahorro el mismo día que te pagan y sacate de encima la decisión mensual.',
      body: [
        'No hace falta acordarte de ahorrar todos los meses: podés dejar que lo haga la banca en línea por vos. Configurá una transferencia automática, programada para el mismo día en que te llega el sueldo, hacia una cuenta de ahorro separada.',
        'La clave está en el orden: si el dinero sale antes de que puedas verlo en tu cuenta corriente, nunca llega a sentirse como plata disponible para gastar. Elegí un monto fijo o un porcentaje que puedas sostener sin ahogarte, y dejá que se repita solo, mes tras mes.',
        'Cada seis meses, dale una mirada: si tus ingresos o gastos cambiaron, ajustá el monto. El objetivo no es la cifra perfecta desde el primer día, sino que la transferencia siga ocurriendo sin que vos tengas que acordarte.',
      ],
      publishedAt: '2026-06-14',
    },
    {
      id: 'desafio-52-semanas',
      categoryId: 'ahorro',
      badge: 'Ahorro',
      title: 'El Desafío de las 52 Semanas',
      excerpt: 'Empezá ahorrando poco y subí el monto cada semana. Al cabo de un año, ese hábito progresivo se convierte en un fondo considerable.',
      body: [
        'La idea es simple: arrancás con un monto chico la primera semana y lo vas subiendo semana a semana durante todo el año. Como el incremento es gradual, el ahorro nunca se siente como un salto brusco al bolsillo.',
        'Podés elegir el ritmo según lo que te acomode: empezar con $200 y subir de a $200 por semana te deja, en la semana 52, un total acumulado de $275.600. Si podés ir más rápido, arrancar con $500 y sumar $500 cada semana cierra el año en $689.000.',
        'Lo que importa no es competir por el modo más exigente, sino elegir uno que puedas sostener sin sentirte ahogado. Un desafío que abandonás a la semana 10 ahorra menos que uno tranquilo que llegás a completar.',
      ],
      publishedAt: '2026-06-07',
    },
    {
      id: 'empezar-con-lo-que-tenes',
      categoryId: 'ahorro',
      badge: 'Ahorro',
      title: 'La Importancia de Empezar con lo que Tenés',
      excerpt: 'No hace falta una gran cantidad para arrancar a ahorrar. Lo que construye el hábito es la constancia, no el monto inicial.',
      body: [
        'Es común pensar que ahorrar o invertir requiere una suma grande para que valga la pena. Pero lo que realmente marca la diferencia es dar el primer paso, sea cual sea el monto disponible — el hábito se construye con la repetición, no con la cifra.',
        'Guardar poco cada semana puede parecer insignificante al principio, pero fortalece la disciplina, baja la ansiedad de no estar haciendo nada por tu futuro, y con el tiempo esas cantidades chicas se suman hasta convertirse en una base real.',
        'El momento perfecto para empezar casi nunca llega — siempre parece que falta un poco más de plata o de orden. Cuanto antes arranques, más tiempo tiene ese ahorro para crecer. Hoy es mejor momento que la semana que viene.',
      ],
      publishedAt: '2026-05-31',
    },
    {
      id: 'colchon-para-imprevistos',
      categoryId: 'ahorro',
      badge: 'Ahorro',
      title: 'Un Colchón para lo Inesperado',
      excerpt: 'Una reparación, un imprevisto de salud, un mes flaco: tener un colchón aparte evita que un imprevisto se convierta en deuda.',
      body: [
        'Un colchón para lo inesperado es plata reservada específicamente para eso que no podés planificar: se rompe el auto, aparece un gasto médico, se corta un ingreso por un mes. Su función no es rendir — es estar ahí, disponible, el día que la necesites.',
        'Tenerlo armado cambia cómo enfrentás los imprevistos: en vez de recurrir a la tarjeta de crédito o a un préstamo caro, lo cubrís con lo que ya tenías guardado. Un buen punto de partida es apuntar a cubrir al menos un mes de tus gastos básicos — vivienda, servicios, comida, transporte.',
        'Guardalo en una cuenta fácil de acceder en una emergencia real, pero no tan a mano como para tentarte a usarlo en gastos que no son urgentes. Y revisalo de tanto en tanto: si tu situación cambia — una familia que crece, un gasto fijo nuevo — el colchón también debería ajustarse.',
      ],
      publishedAt: '2026-05-24',
    },
    {
      id: 'nombra-tus-ahorros',
      categoryId: 'ahorro',
      badge: 'Ahorro',
      title: 'La Importancia de Nombrarle tus Ahorros',
      excerpt: 'Ahorrar "porque sí" se abandona rápido. Ponerle un nombre concreto a la meta le da sentido a cada peso que guardás.',
      body: [
        'Ahorrar sin un propósito claro es fácil de abandonar a la primera excusa. En cambio, cuando cada depósito tiene un destino concreto — un viaje, un colchón de emergencia, un gusto que te vas a dar — se convierte en un paso hacia algo que realmente te importa.',
        'No hace falta que sea sofisticado: "Viaje a Bariloche 2027" motiva mucho más que una cuenta llamada simplemente "Ahorros". Ponerle nombre a la meta de tu fondo de emergencia — "Tranquilidad Financiera", por ejemplo — también ayuda a recordar para qué está ahí.',
        'Un truco simple: escribí el nombre de tu meta en algún lugar visible — la puerta del refrigerador, el fondo de pantalla del celular. Verlo seguido es lo que sostiene la motivación cuando el ahorro deja de sentirse como una obligación y empieza a sentirse como un objetivo propio.',
      ],
      publishedAt: '2026-05-17',
    },
    {
      id: 'protegerse-de-estafas-en-linea',
      categoryId: 'alertas',
      badge: 'Alertas',
      title: 'Cómo Protegerse de Estafas en Línea',
      excerpt: 'Un mensaje que promete un premio que nunca pediste es la señal más clara de alerta. Nunca compartas datos bancarios por esa vía.',
      body: [
        'Los mensajes que anuncian un premio o un reembolso inesperado —sin que hayas participado en nada— son una de las tácticas más comunes para robar datos personales y bancarios. Cuanto más urgente suena el mensaje, más motivo para desconfiar: la urgencia está diseñada para que no pares a pensar.',
        'Ninguna institución seria te va a pedir contraseñas, números de tarjeta o claves por mensaje de texto o correo. Evitá hacer clic en enlaces de fuentes que no reconocés, y si el mensaje dice venir de una empresa conocida, contactala vos directamente por sus canales oficiales para confirmar.',
        'Si sospechás que caíste en un intento de estafa, reportá el mensaje, bloqueá al remitente y revisá tus movimientos bancarios de los días siguientes. Prevenir siempre sale más barato que lamentar.',
      ],
      publishedAt: '2026-05-10',
    },
    {
      id: 'cuotas-sin-interes',
      categoryId: 'alertas',
      badge: 'Alertas',
      title: 'Cuidado con las Cuotas "Sin Interés"',
      excerpt: 'El precio "sin interés" a veces ya viene inflado. Compará siempre contra el valor al contado antes de comprometerte a cuotas.',
      body: [
        'Cuando una compra se ofrece en cuotas "sin interés", vale la pena mirar con atención: una táctica común es inflar el precio del producto de entrada, para compensar por adelantado los intereses que "no" vas a pagar en las cuotas.',
        'Un televisor de $10.000 al contado puede aparecer en 12 cuotas "sin interés" de $1.000 — es decir, $12.000 en total. Ese es el costo real de la oferta, aunque en ningún cargo individual figure la palabra "interés".',
        'Antes de comprometerte, preguntá siempre por el precio al contado y compará. Y no te saltees la letra chica: ahí suelen estar los cargos adicionales o las condiciones que hacen que la oferta deje de ser tan conveniente como parece.',
      ],
      publishedAt: '2026-05-03',
    },
    {
      id: 'suscripciones-renovacion-automatica',
      categoryId: 'alertas',
      badge: 'Alertas',
      title: 'La Trampa de las Renovaciones Automáticas',
      excerpt: 'Es fácil olvidar una suscripción activa si no usás el servicio seguido. El cobro, en cambio, no se olvida de vos.',
      body: [
        'La mayoría de las apps y servicios de suscripción están configurados para renovarse solos cada mes. Es una comodidad cuando el servicio se usa a diario — y un gasto silencioso cuando dejó de usarse hace tiempo y nadie se acordó de cancelarlo.',
        'Revisar tu cartola bancaria con cierta frecuencia es la única forma confiable de detectar estos cargos recurrentes. No hace falta hacerlo todos los días: alcanza con un repaso mensual, línea por línea, prestando atención a lo que se repite.',
        'Hacé una lista de tus suscripciones activas y preguntate, una por una, si realmente le sacás uso. Cancelar las que no aportan no solo libera plata cada mes — también simplifica tu vida digital y te saca de encima el peso de llevar la cuenta de tantos servicios a la vez.',
      ],
      publishedAt: '2026-04-26',
    },
    {
      id: 'cae-mas-alla-de-la-tasa',
      categoryId: 'alertas',
      badge: 'Alertas',
      title: 'El CAE: Más Allá de la Tasa de Interés',
      excerpt: 'La tasa de interés no cuenta toda la historia de un crédito. El CAE suma comisiones y seguros para mostrar el costo real.',
      body: [
        'Cuando se compara un crédito, es tentador fijarse solo en la tasa de interés mensual que ofrece cada institución. Pero ese número, solo, puede ser engañoso: no incluye comisiones, seguros ni otros cargos que también forman parte del costo final.',
        'El CAE — Carga Anual Equivalente — junta todo eso en un solo número: tasa de interés, comisiones de apertura o administración, seguros asociados y cualquier otro cargo obligatorio. Es la forma más justa de comparar dos ofertas de crédito entre sí, porque muestra el costo total y no solo una parte.',
        'Las instituciones financieras están obligadas a mostrarte el CAE en el contrato — no hace falta calcularlo vos mismo. Antes de comprometerte con un préstamo, pedilo, comparalo entre opciones, y tomá la decisión con el costo completo sobre la mesa, no solo con la tasa que suena más linda en el aviso.',
      ],
      publishedAt: '2026-04-19',
    },
    {
      id: 'ofertas-por-tiempo-limitado',
      categoryId: 'alertas',
      badge: 'Alertas',
      title: 'La Psicología de las Ofertas "Por Tiempo Limitado"',
      excerpt: '"Solo por hoy" apela al miedo a perderte algo, no a que sea una buena oferta. Si de verdad es buena, va a seguir siéndolo mañana.',
      body: [
        'Frases como "solo por hoy" o "hasta agotar existencias" no están ahí para informarte — están diseñadas para generar una sensación de escasez y activar el miedo a perderte algo (FOMO), empujándote a decidir rápido y sin pensarlo demasiado.',
        'Bajo presión de tiempo, el cerebro prioriza la compra inmediata por sobre la reflexión: un producto puede sentirse más valioso solo por estar atado a una oferta limitada, aunque su valor real no haya cambiado en nada.',
        'Antes de comprar por el apuro de la oferta, preguntate si realmente necesitás el producto o si estás reaccionando al límite de tiempo. Una oferta genuinamente buena casi siempre sigue siendo buena al día siguiente — tomarte ese margen para pensar no te cuesta la oferta, pero sí te puede ahorrar un arrepentimiento.',
      ],
      publishedAt: '2026-04-12',
    },
    {
      id: 'ahorrar-no-es-invertir',
      categoryId: 'educacion-financiera',
      badge: 'Educación Financiera',
      title: 'Ahorrar no es lo Mismo que Invertir',
      excerpt: 'El ahorro te da seguridad y acceso inmediato. La inversión busca crecimiento, pero asume riesgo. Ninguno reemplaza al otro.',
      body: [
        'Ahorrar e invertir suelen mencionarse juntos, pero cumplen funciones distintas. Ahorrar es guardar plata para tenerla disponible cuando haga falta: prioriza la seguridad y el acceso rápido, aunque eso signifique renunciar a un rendimiento mayor.',
        'Invertir, en cambio, es poner esa plata a trabajar con el objetivo de que crezca con el tiempo — y eso implica asumir algo de riesgo, porque el valor de una inversión puede subir o bajar según el mercado. Suele requerir, además, un horizonte más largo para dar resultados.',
        'Antes de meterte a invertir, conviene tener un colchón de ahorro básico armado: te permite cubrir un imprevisto sin tener que liquidar una inversión a destiempo, y te da la tranquilidad necesaria para invertir con la cabeza fría, no con apuro.',
      ],
      publishedAt: '2026-04-05',
    },
    {
      id: 'gastos-fijos-y-variables',
      categoryId: 'educacion-financiera',
      badge: 'Educación Financiera',
      title: 'Diferenciación de Gastos Fijos y Variables',
      excerpt: 'Los fijos se repiten cada mes y son previsibles. Los variables cambian según tus decisiones — y ahí está tu margen para ajustar.',
      body: [
        'Los gastos fijos son los que se repiten mes a mes con un monto similar: el arriendo, el plan de celular, el internet, un seguro. Son previsibles, y por eso son más fáciles de planificar dentro de un presupuesto — sabés de antemano que van a estar ahí.',
        'Los gastos variables, en cambio, dependen de tus decisiones del día a día: la comida, las salidas, una compra personal. Fluctúan de un mes a otro, lo que los hace más difíciles de prever, pero también más flexibles — ahí es donde tenés el mayor margen para ajustar cuando necesitás liberar plata.',
        'Distinguir uno de otro es el primer paso para un presupuesto realista: los fijos te dicen cuánto necesitás sí o sí cada mes, y los variables te muestran dónde tenés margen real de decisión si algo necesita cambiar.',
      ],
      publishedAt: '2026-03-29',
    },
    {
      id: 'proposito-de-un-presupuesto',
      categoryId: 'educacion-financiera',
      badge: 'Educación Financiera',
      title: 'El Propósito de un Presupuesto',
      excerpt: 'Un presupuesto no es una cárcel para tu plata — es el mapa que te muestra cuánto entra, cuánto sale y a dónde podés llevarla.',
      body: [
        'Lejos de ser una restricción, un presupuesto es simplemente un plan que detalla tus ingresos y gastos durante un período — generalmente un mes. Su función es mostrarte con claridad cuánto entra, cuánto sale, y en qué se va, para que puedas decidir con esa información y no a ciegas.',
        'Esa visibilidad tiene efectos concretos: te ayuda a notar patrones de gasto que no habías registrado, a ajustar hábitos que te están sacando de tu presupuesto, y a asignar conscientemente una parte de tus ingresos al ahorro en vez de dejarlo librado al azar.',
        'No hace falta que sea perfecto desde el primer mes. Anotá tus ingresos, separá tus gastos fijos de los variables, y después de unas semanas revisá qué patrones aparecen. Un presupuesto que se ajusta con el tiempo vale más que uno perfecto que abandonás a la segunda semana.',
      ],
      publishedAt: '2026-03-22',
    },
    {
      id: 'interes-compuesto',
      categoryId: 'educacion-financiera',
      badge: 'Educación Financiera',
      title: 'Entendiendo el Interés Compuesto',
      excerpt: 'Los intereses generan sus propios intereses. A tu favor en el ahorro, en contra tuya en una deuda que no pagás a tiempo.',
      body: [
        'El interés compuesto ocurre cuando los intereses que generás sobre un ahorro o una inversión empiezan, a su vez, a generar sus propios intereses. No solo ganás sobre tu capital inicial, sino también sobre lo que ya habías ganado en períodos anteriores — por eso el crecimiento se acelera con el tiempo.',
        'A tu favor, esto significa que cuanto antes empieces a ahorrar o invertir, más tiempo tiene tu plata para crecer de forma exponencial — es especialmente potente para metas de largo plazo, como una jubilación o una educación futura.',
        'En contra tuya, el mismo mecanismo aplica a las deudas con saldos rotativos, como una tarjeta de crédito: si no pagás a tiempo, los intereses se acumulan sobre el saldo impago y la deuda puede crecer más rápido de lo esperado. Entender esto es clave para que el interés compuesto trabaje para vos, y no en tu contra.',
      ],
      publishedAt: '2026-03-15',
    },
    {
      id: 'sueldo-bruto-vs-liquido',
      categoryId: 'educacion-financiera',
      badge: 'Educación Financiera',
      title: 'Sueldo Bruto vs. Sueldo Líquido',
      excerpt: 'El sueldo bruto es el número del contrato. El líquido es lo que realmente entra a tu cuenta — y es con ese que hay que presupuestar.',
      body: [
        'El sueldo bruto es el monto total que figura en tu contrato: incluye tu salario base, más bonificaciones, horas extras y otros beneficios, antes de cualquier descuento. Es un número real, pero no es el que vas a poder gastar.',
        'El sueldo líquido es lo que efectivamente llega a tu cuenta bancaria, después de descontar la AFP, la salud, los impuestos y cualquier otro descuento contractual. La diferencia entre ambos puede ser considerable, y confundirlos es una de las formas más comunes de armar un presupuesto que no cierra.',
        'La regla es simple: planificá siempre en base a tu sueldo líquido, nunca al bruto. Es la única cifra que refleja de verdad cuánta plata vas a tener disponible para gastar, ahorrar, y cubrir tus gastos fijos cada mes.',
      ],
      publishedAt: '2026-03-08',
    },
    {
      id: 'antes-de-comprar-preguntate-esto',
      categoryId: 'tips-financieros',
      badge: 'Tips Financieros',
      title: 'Antes de Comprar, Preguntate Esto',
      excerpt: '¿Lo necesito, lo quiero, o solo lo vi y me dieron ganas? Tres preguntas simples antes de sacar la billetera.',
      body: [
        'Frenar un segundo antes de pagar puede ser una de las herramientas más simples para mantener tus finanzas bajo control. La primera pregunta es la más básica: ¿lo necesito de verdad? Si no cae dentro de lo esencial —comida, vivienda, ropa básica— probablemente no sea una necesidad.',
        'La segunda pregunta separa el deseo del impulso: ¿realmente lo querés, o hace rato que le venís dando vueltas y de verdad suma algo a tu vida? Y la tercera va al hueso del impulso puro: ¿lo viste recién y te dieron ganas ahí mismo? Las compras motivadas por un impulso momentáneo son las que más arrepentimiento generan después.',
        'Nombrar la razón real detrás de una compra te ayuda a notar patrones en cómo gastás, y con el tiempo, a distinguir mejor qué es lo que de verdad valorás. No se trata de no comprar nunca por gusto — se trata de saber, con honestidad, por qué lo estás haciendo.',
      ],
      publishedAt: '2026-03-01',
    },
    {
      id: 'separa-tu-plata-en-cuentas',
      categoryId: 'tips-financieros',
      badge: 'Tips Financieros',
      title: 'Separá tu Plata en Cuentas Distintas',
      excerpt: 'Una cuenta para lo fijo, otra para el día a día, otra para ahorro. Verlo separado hace mucho más difícil gastar de más.',
      body: [
        'Cuando toda tu plata vive en una sola cuenta, es fácil perder la noción de cuánto es realmente disponible para gastar y cuánto ya tiene un destino. Separar el dinero según su propósito es una forma simple de recuperar ese control.',
        'Una cuenta puede concentrar los gastos fijos —arriendo, servicios, seguros— para asegurarte de que siempre estén cubiertos. Otra, el día a día: comida, transporte, salidas, revisada seguido para no pasarte de la raya. Y una tercera, de ahorro, idealmente algo menos accesible, para que no se convierta en la primera opción cuando falta plata a fin de mes.',
        'Programar una transferencia automática a cada cuenta apenas te llega el sueldo hace que el sistema funcione solo, sin depender de la memoria ni de la fuerza de voluntad de todos los meses.',
      ],
      publishedAt: '2026-02-22',
    },
    {
      id: 'el-habito-de-pagarte-primero',
      categoryId: 'tips-financieros',
      badge: 'Tips Financieros',
      title: 'El Hábito de Pagarte a Vos Primero',
      excerpt: 'Separá tu ahorro apenas te pagan, antes de cualquier otro gasto. Lo que sobra a fin de mes casi nunca sobra.',
      body: [
        'La estrategia de "pagarte a vos primero" invierte el orden habitual: en lugar de ahorrar lo que queda después de pagar todo, separás el ahorro apenas te llega el ingreso, antes de destinarlo a cualquier otra cosa. La cantidad puede ser chica — lo que importa es que sea constante.',
        'El beneficio va más allá de juntar plata: te ayuda a construir un colchón para imprevistos, refuerza la disciplina financiera, y con el tiempo te vuelve menos dependiente de "lo que sobre" a fin de mes — que, en la práctica, casi nunca sobra nada.',
        'Definí un monto que puedas sostener sin ahogarte, automatizá la transferencia para que ocurra sola, y reevaluala cada tanto si tus ingresos cambian. Es un cambio de orden simple, pero con el tiempo transforma por completo tu relación con el ahorro.',
      ],
      publishedAt: '2026-02-15',
    },
    {
      id: 'revision-semanal-de-gastos',
      categoryId: 'tips-financieros',
      badge: 'Tips Financieros',
      title: 'Revisión Semanal de Gastos',
      excerpt: 'Diez minutos cada domingo alcanzan para notar un desvío antes de que se convierta en un problema a fin de mes.',
      body: [
        'Dedicar diez minutos cada domingo a repasar en qué gastaste durante la semana puede ser una de las herramientas más simples para mantener tus finanzas bajo control. No hace falta más que eso para notar patrones y corregir el rumbo antes de que un pequeño desvío se convierta en un problema grande a fin de mes.',
        'La revisión semanal te muestra en qué categorías se te está yendo más plata de la esperada, y te da la chance de ajustar sobre la marcha — es mucho más fácil hacer pequeños ajustes seguidos que intentar corregir todo de golpe cuando ya pasó el mes entero.',
        'Fijate un horario regular, siempre el mismo día, y usalo también para revisar si tus gastos reflejan lo que de verdad te importa. Con el tiempo, esta costumbre reduce bastante la ansiedad de no saber bien en qué se te fue la plata.',
      ],
      publishedAt: '2026-02-08',
    },
    {
      id: 'usa-el-vuelto-a-tu-favor',
      categoryId: 'tips-financieros',
      badge: 'Tips Financieros',
      title: 'Usá el Vuelto a tu Favor',
      excerpt: 'Las monedas sueltas del vuelto parecen no valer nada — hasta que juntás varias semanas seguidas y ves cuánto sumaron.',
      body: [
        'Cuando pagás en efectivo, es fácil no darle importancia al vuelto que te dan — son monedas o billetes chicos que, sueltos, no parecen valer gran cosa. Pero juntados con constancia, suman mucho más de lo que uno se imagina.',
        'Una alcancía sigue siendo una herramienta efectiva: cada vez que recibís vuelto, lo guardás ahí, sin pensarlo dos veces. Ver cómo se va llenando es, en sí mismo, un motivador para seguir. Si preferís algo más moderno, hay apps de ahorro que redondean tus compras automáticamente y transfieren la diferencia a una cuenta aparte.',
        'No importa el método que elijas — lo que cuenta es empezar. Convertir ese vuelto disperso en un fondo de emergencia o en el ahorro para una meta puntual es una forma casi invisible de sumarle estabilidad a tus finanzas.',
      ],
      publishedAt: '2026-02-01',
    },
  ],

  // Categorías de Gasto Fijo / vencimiento — definen ícono y color en la UI.
  fixedExpenseCategories: [
    { id: 'streaming',  name: 'Streaming',           icon: 'play',    color: 'violet' },
    { id: 'servicios',  name: 'Servicios Básicos',   icon: 'bolt',    color: 'blue' },
    { id: 'tarjeta',    name: 'Tarjeta de Crédito',  icon: 'card',    color: 'orange' },
    { id: 'alquiler',   name: 'Vivienda',            icon: 'key',     color: 'green' },
    { id: 'creditos',   name: 'Créditos y Préstamos', icon: 'percent', color: 'red' },
    { id: 'salud',      name: 'Salud',               icon: 'heart',   color: 'cyan' },
    { id: 'transporte', name: 'Transporte',          icon: 'car',     color: 'blue' },
    { id: 'educacion',  name: 'Educación',           icon: 'cap',     color: 'violet' },
    { id: 'otros',      name: 'Otros',               icon: 'dots',    color: 'grey' },
  ],

  // Pool de retos semanales. El reto vigente NO se sortea: sale de este mismo
  // orden, avanzando una posición por semana (ver challengeForWeek() en
  // app.js), así todos ven el mismo reto la misma semana y recargar la página
  // nunca lo cambia. Agregar retos al final es seguro; reordenar el pool
  // cambia qué reto toca cada semana, pero el historial ya finalizado se
  // resuelve por `id` y no se rompe.
  weeklyChallenges: [
    { id: 'sin-gastos-hormiga',   title: 'Sin gastos hormiga',    description: 'Evitá gastos chicos e innecesarios: cafés de más, antojos, compras impulsivas menores a $3.000.' },
    { id: 'chau-una-suscripcion', title: 'Chau una suscripción',  description: 'Cancelá al menos una suscripción que no estés usando (streaming, apps, gimnasio, etc.).' },
    { id: 'semana-de-venta',      title: 'Semana de venta',       description: 'Vendé o intercambiá algo que no usás (ropa, tecnología, libros) y sumá esa plata a tu ahorro.' },
    { id: 'ahorro-intacto',       title: 'Ahorro intacto',        description: 'No toques ni un peso de tus ahorros esta semana, pase lo que pase.' },
    { id: 'registro-total',       title: 'Registro total',        description: 'Anotá cada peso que gastás, por chico que sea, toda la semana.' },
    { id: 'semana-sin-delivery',  title: 'Semana sin delivery',   description: 'Nada de Uber Eats ni Rappi: cociná o llevá tu colación todos los días.' },
    { id: 'solo-efectivo',        title: 'Solo efectivo',         description: 'Retirá un monto fijo para la semana y usá solo eso, nada de tarjeta.' },
    { id: 'cazador-de-precios',   title: 'Cazador de precios',    description: 'Elegí una compra pendiente y comparala en al menos dos lugares antes de pagarla.' },
    { id: 'dia-cero',             title: 'Día cero',              description: 'Elegí un día esta semana en el que no gastes absolutamente nada.' },
    { id: 'detox-de-compras',     title: 'Detox de compras',      description: 'Dejá de seguir, aunque sea por esta semana, las cuentas o apps que más ganas de comprar te dan.' },
    { id: 'revisa-tu-cartola',    title: 'Revisá tu cartola',     description: 'Repasá tu último estado de cuenta y marcá los gastos que no volverías a hacer.' },
    { id: 'ahorro-hormiga',       title: 'Ahorro hormiga',        description: 'Guardá al menos $1.000 todos los días de la semana, aunque sea en una alcancía.' },
    { id: 'lista-antes-de-ir',    title: 'Lista antes de ir',     description: 'No entres al supermercado sin una lista armada de antemano.' },
    { id: 'fuera-del-fomo',       title: 'Fuera del FOMO',        description: 'No compres nada solo porque está "en oferta" o por tiempo limitado.' },
    { id: 'cuenta-tus-intereses', title: 'Cuenta tus intereses',  description: 'Si tenés deudas o compras en cuotas, calculá cuánto te están costando en intereses.' },
    { id: 'regalo-con-manos',     title: 'Regalo con manos',      description: 'Si tenés que regalar algo esta semana, que sea hecho por vos, no comprado.' },
    { id: 'un-no-con-onda',       title: 'Un "no" con onda',      description: 'Decile que no a un plan o salida que no podés costear esta semana.' },
    { id: 'vaciar-la-despensa',   title: 'Vaciar la despensa',    description: 'Cociná con lo que ya tenés en casa antes de comprar algo nuevo.' },
    { id: 'foto-a-tus-ingresos',  title: 'Foto a tus ingresos',   description: 'Anotá con claridad cuánto entra realmente este mes (sueldo líquido, extras, etc.).' },
    { id: 'transporte-low-cost',  title: 'Transporte low cost',   description: 'Elegí la opción más económica para moverte toda la semana (Bip!, bici, a pie).' },
    { id: 'compra-pensada',       title: 'Compra pensada',        description: 'Si necesitás comprar algo esta semana, buscá primero si existe de segunda mano.' },
    { id: 'fondo-aparte',         title: 'Fondo aparte',          description: 'Empezá o sumá a un fondo de emergencia, aunque sea con $5.000.' },
    { id: 'chequeo-gastos-fijos', title: 'Chequeo de gastos fijos', description: 'Revisá luz, agua, internet y plan de celular: buscá algo para renegociar.' },
    { id: 'closet-challenge',     title: 'Clóset challenge',      description: 'No compres ropa nueva esta semana; usá lo que ya tenés.' },
    { id: 'a-medias',             title: 'A medias',              description: 'Buscá compartir algún gasto fijo (streaming, compras grandes) con alguien más.' },
    { id: 'el-gasto-que-pesa',    title: 'El gasto que pesa',     description: 'Identificá un gasto que te genera culpa y decidí a conciencia si lo mantenés.' },
    { id: 'sin-credito',          title: 'Sin crédito',           description: 'Usá solo débito, Bip! o efectivo, nada de tarjeta de crédito.' },
    { id: 'ajuste-de-ruta',       title: 'Ajuste de ruta',        description: 'Mirá cómo venías gastando últimamente y ajustá una meta para adelante.' },
    { id: 'uno-menos',            title: 'Uno menos',             description: 'Elegí un gasto fijo mensual y reducilo o cancelalo definitivamente.' },
    { id: 'balance-de-la-semana', title: 'Balance de la semana',  description: 'Mirá cuánto lograste ahorrar o gastar mejor esta semana, sin juzgarte, solo con los datos.' },
  ],

  // Frases cortas para la card "Dosis de Calma" — rotan por fecha, no por azar,
  // así la frase del día es estable si el usuario recarga la página.
  calmQuotes: [
    'La calma financiera no es tener más plata. Es saber exactamente dónde está la que tenés.',
    'Un gasto anotado pesa menos que un gasto que da vueltas en la cabeza.',
    'No hace falta ganar más para dormir tranquilo. Hace falta saber a dónde va cada peso.',
    'El orden en tus cuentas de hoy es el susto que no vas a tener mañana.',
    'Ahorrar no es privarte. Es decidir con anticipación en vez de con apuro.',
  ],
};
